4467 - Untranslatable UI terms
huridocs/uwazidocs pull request #4772
Opened 2022-06-22 20:26 UTC by Zasa-san

fixes #4467 #4782

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2022-06-24 16:04 UTC, mfacar requested changes
@Zasa-san, LGTM, there is only a point I think is not covered
```select "Create group" below to group filters under a label e.g ("Documents "or "People")``` although ```Create group``` has a translation it is not reflected in this message at the page ```Filters```

2022-06-24 16:04 UTC, mfacar commented on app/api/migrations/migrations/83-add_system_key_translations/system_keys.csv
> +"Create user","Create user",
the key used in code is ```Create User``` instead of ```Create user```

2022-06-24 17:45 UTC, Zasa-san commented on app/api/migrations/migrations/83-add_system_key_translations/system_keys.csv
> +"Create user","Create user",
Good catch!

2022-06-24 17:47 UTC, Zasa-san commented
> @Zasa-san, LGTM, there is only a point I think is not covered `select "Create group" below to group filters under a label e.g ("Documents "or "People")` although `Create group` has a translation it is not reflected in this message at the page `Filters`

It's under the key `Filters configuration example`

2022-06-24 19:53 UTC, mfacar commented
> Filters configuration example

Right, but since it is a hint to guide about how to create a group, I think the expectation is to see the actual label of the button as the suggestion because if it is translated with something else, the message doesn't have sense.

2022-06-26 19:15 UTC, merged

2022-06-29 15:09 UTC, llfinch commented
Hi all! I just want to flag that in staging instances, it shows that the Multiselect property has been spelled wrong ("Miltiselect"): 

![image](https://user-images.githubusercontent.com/56080527/176471128-a0e560b7-e62e-4e95-806d-780bf8a6f053.png)

Which means it also shows as spelled wrong in the template builder: 

![image](https://user-images.githubusercontent.com/56080527/176471246-25de4b03-8d2f-4004-ad3d-a30d56207717.png)

2022-06-29 15:26 UTC, Zasa-san commented
> Hi all! I just want to flag that in staging instances, it shows that the Multiselect property has been spelled wrong ("Miltiselect"):
> 
> ![image](https://user-images.githubusercontent.com/56080527/176471128-a0e560b7-e62e-4e95-806d-780bf8a6f053.png)
> 
> Which means it also shows as spelled wrong in the template builder:
> 
> ![image](https://user-images.githubusercontent.com/56080527/176471246-25de4b03-8d2f-4004-ad3d-a30d56207717.png)

Thanks @llfinch! I'll prepare a fix for that.