5129 - Fix settings navigation on mobile
huridocs/uwazidocs pull request #5293
Opened 2022-11-08 18:36 UTC by Zasa-san

fixes #5129

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2022-11-09 20:55 UTC, mfacar requested changes
LGTM, I just have one observation, please check the comment in the code. 
Everything works as expected, good job, although I'm not very convinced about the size of the label and the back button, of course, this is how it is in the design so don't mind about it 😄 .

2022-11-09 20:55 UTC, mfacar commented on app/react/Pages/components/PagesList.js
> +          </I18NLink>
This seems to be a good candidate to be extracted as a component because it's used in at least four other places, what do you think?

2022-11-10 14:23 UTC, Zasa-san commented on app/react/Pages/components/PagesList.js
> +          </I18NLink>
Yes, that makes sense.

2022-11-11 20:05 UTC, mfacar approved these changes

2022-11-11 20:10 UTC, merged