5570 quick new relationships UI crud
huridocs/uwazidocs pull request #5760
Opened 2023-04-28 08:52 UTC by LaszloKecskes

fixes #5570 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-05-02 22:24 UTC, fnocetti requested changes
Nice work!
Please, check the comments and the failing tests.
Also, the functionality seems to work as expected. I think what needs just an extra bit of work is that the list of relationships shows in a misleading way. When you create a relationships from entity A to B, if you then visit entity B, the list will shows the arrow pointing in the wrong direction, and the current entity in both ends (once as sharedId, and once as a title). I think it could be useful to just show both sides for each relationships, even if the current entity at view shows many times.

2023-05-02 22:24 UTC, fnocetti commented on app/api/relationships.v2/model/Relationship.ts
> +  static getSharedIds(relationships: Relationship[]): Set<string> {
I can't seem to find a use of this method. Please check.

2023-05-02 22:24 UTC, fnocetti commented on app/api/relationships.v2/services/GetRelationshipService.ts
> +    const involvedSharedIds: Set<string> = new Set(
Maybe this is were you meant to use the static method in Relationships.ts?

2023-05-03 07:26 UTC, LaszloKecskes commented
> 

That's a nice catch. :)

2023-05-03 07:29 UTC, LaszloKecskes commented on app/api/relationships.v2/model/Relationship.ts
> +  static getSharedIds(relationships: Relationship[]): Set<string> {
You've found it.

2023-05-03 07:29 UTC, LaszloKecskes commented on app/api/relationships.v2/services/GetRelationshipService.ts
> +    const involvedSharedIds: Set<string> = new Set(
Precisely.

2023-05-03 18:20 UTC, fnocetti approved these changes
LGTM!

2023-05-04 08:41 UTC, merged