Translations v2
huridocs/uwazidocs pull request #5859
Opened 2023-05-24 13:06 UTC by daneryl

fixes #3344 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-05-26 11:55 UTC, LaszloKecskes commented on app/api/i18n.v2/model/Translation.ts
> +    type?: 'Entity' | 'Relationship Type' | 'Uwazi UI' | 'Thesaurus';
Can a context not have type?

2023-05-26 12:30 UTC, fnocetti commented on app/api/i18n.v2/model/Translation.ts
> +    type?: 'Entity' | 'Relationship Type' | 'Uwazi UI' | 'Thesaurus';
Also, maybe its a good idea to extract the type to it's own type definition.

2023-05-29 06:36 UTC, daneryl commented on app/api/i18n.v2/model/Translation.ts
> +    type?: 'Entity' | 'Relationship Type' | 'Uwazi UI' | 'Thesaurus';
No, i do not think type should be optional, going to change that and extract the type also :+1:

2023-06-12 09:17 UTC, LaszloKecskes commented on app/api/i18n.v2/schemas/TranslationDBO.ts
> +  language: string; // should be an enum ?
Good question. If we have a list of supported languages somewhere with their keys, probably we should make use of that, where we define languages.

2023-06-12 09:19 UTC, LaszloKecskes commented on app/api/i18n.v2/services/CreateTranslationsService.ts
> +  language: string; // should be an enum ?
Same as in the DBO, probably yes.

2023-06-12 09:37 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +    return this.getCollection().deleteMany({ 'context.id': contextId });
For this, add an index on the collection just for context.id

2023-06-12 09:37 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +    return this.getCollection().deleteMany({ language });
Same: an index for language.

2023-06-12 09:40 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +    return this.getCollection().deleteMany({ 'context.id': contextId });
Let's probably make it a compound with the order (context.id, key), since later on there are queries that use only these two.

2023-06-12 09:45 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +        for await (const dbt of dbtrans) {
With Fede we usually use 
```
while(await cursor.hasNext()) {
    const item = await cursor.next();
```
It's a lot less pretty, but avoids the `/* eslint-disable no-restricted-syntax */` problem. On the downside, it also adds a lot of no-await-in-loops. Maybe we could discuss disabling that one on the tech call, since we seem to use it a lot.

2023-06-12 09:55 UTC, LaszloKecskes commented on app/api/i18n.v2/migrations/index.js
> +        flatTranslations.concat(
I think concat copies both arrays, so inside a reduce this can be slow. Alternatives can be pushing one by one inside reduce and always pass the reference to the array, or I think this one might be solved by a douple map, then flat().

2023-06-12 09:57 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +    return this.getCollection().deleteMany({ language });
Scratch that, the current one covers this.

2023-06-12 10:20 UTC, LaszloKecskes commented on app/api/i18n.v2/services/specs/DeleteTranslationsService.spec.ts
> +  translations_v2: [
This is a common comment for all tests: in common.v2/testing we've started with experimenting how we could use the fixture factory for v2, so if you'd like, you could add to that next time. For now, I don't think it is necessary.

2023-06-12 10:32 UTC, LaszloKecskes commented on app/api/i18n/specs/translations_v2_support.spec.ts
> +      it('should properly change context name, key names, values for the keys changed and deleteProperties, and create new values as new translations (OMG !)', async () => {
Left an extra comment at the end of the text description.

2023-06-12 10:37 UTC, LaszloKecskes commented on app/api/i18n/v2_support.ts
> +    return translation.contexts.reduce(
Same comment as in the migration: try to go without the concat in reduce.

2023-06-12 10:42 UTC, LaszloKecskes commented on app/api/i18n/v2_support.ts
> +export const createTranslationsV2 = async (translation: TranslationType) => {
For the next couple, where the dependency tree's are initialized: we usually write out the initialization separately, so they are easier to use. For data sources, see files named data_source_defaults, for services, see files named service_factories. Relationships.v2 is the best example, since that is a lot.

2023-06-12 10:53 UTC, LaszloKecskes commented on app/api/i18n/translations.ts
> +  async save(translation: TranslationType | IndexedTranslations) {
So, the idea is that we save to both until we think we are ready to drop the v1?

2023-06-12 10:58 UTC, LaszloKecskes requested changes
There are a couple of local things, but overall now everything is there I think. The online migration is impressive. :)

It's a pity we can't run the entire api unite test suite with the feature flag on to see what happens.

2023-06-12 14:33 UTC, daneryl commented on app/api/i18n.v2/migrations/index.js
> +        flatTranslations.concat(
done :+1:

2023-06-12 14:34 UTC, daneryl commented on app/api/i18n/v2_support.ts
> +    return translation.contexts.reduce(
done :+1:

2023-06-12 14:35 UTC, daneryl commented on app/api/i18n/translations.ts
> +  async save(translation: TranslationType | IndexedTranslations) {
Yes, this gives us the ability to deactivate if something goes wrong to use the old code, while we work on a fix.

2023-06-12 14:37 UTC, daneryl commented
> There are a couple of local things, but overall now everything is there I think. The online migration is impressive. :)
> 
> It's a pity we can't run the entire api unite test suite with the feature flag on to see what happens.

Thanks for the review, working on some changes, i did run it locally with the flag activated and everything was green btw, but its a good point maybe we should be able to somehow run it on ci ?

2023-06-12 14:39 UTC, daneryl commented on app/api/i18n.v2/services/specs/DeleteTranslationsService.spec.ts
> +  translations_v2: [
Im going to have to change all fixtures on the final iteration, i will add this change to that development :+1:

2023-06-12 14:40 UTC, LaszloKecskes commented on app/api/i18n/translations.ts
> +  async save(translation: TranslationType | IndexedTranslations) {
Nice!

2023-06-13 06:23 UTC, daneryl commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +        for await (const dbt of dbtrans) {
changed to a while :+1:

2023-06-13 08:15 UTC, daneryl commented on app/api/i18n.v2/schemas/TranslationDBO.ts
> +  language: string; // should be an enum ?
Added as a String literal union type

2023-06-13 08:48 UTC, daneryl commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +    return this.getCollection().deleteMany({ 'context.id': contextId });
done :+1:

2023-06-13 08:59 UTC, daneryl commented on app/api/i18n/specs/translations_v2_support.spec.ts
> +      it('should properly change context name, key names, values for the keys changed and deleteProperties, and create new values as new translations (OMG !)', async () => {
removed it :)

2023-06-14 08:50 UTC, daneryl commented on app/api/i18n/v2_support.ts
> +export const createTranslationsV2 = async (translation: TranslationType) => {
done :+1:  thank you, now all transactions.run are proper transactions!

2023-06-19 08:25 UTC, LaszloKecskes commented on app/api/i18n.v2/contracts/TranslationsDataSource.ts
> +  calculateUnexistentKeys(keys: string[]): Promise<string[]>;
Minimal english nitpick, but according to my dictionary it is either: unexisting, nonexistent, or inexistent.

2023-06-19 08:32 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +      items.map(async item =>
I did not catch this last time, but maybe it's not a good idea to use the stream functions parallel, since the underlying structure holding the information is just a regular array. So while it is most likely extremely rare, there might be some race conditions involved (with multiple things triggering a flush at the same time, etc.).

2023-06-19 08:34 UTC, LaszloKecskes commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +      items.map(async item =>
...and actually, later in the same file (updateKeysByContext) it's synchronized through a promise based reduce. I think something like that would be the good approach.

2023-06-19 08:37 UTC, LaszloKecskes commented on app/api/i18n.v2/migrations/index.js
> +const flattenTranslations = (translation, languagesByKeyContext) => {
I don't remember exactly, but should we move this to the normal migrations?

2023-06-19 08:49 UTC, LaszloKecskes requested changes
Aside from those two small things, looks good.

2023-06-19 08:58 UTC, daneryl commented on app/api/i18n.v2/migrations/index.js
> +const flattenTranslations = (translation, languagesByKeyContext) => {
Will move it on the next iteration, for now this migration runs when activating a feature flag

2023-06-19 09:03 UTC, daneryl commented on app/api/i18n.v2/contracts/TranslationsDataSource.ts
> +  calculateUnexistentKeys(keys: string[]): Promise<string[]>;
:+1: changed to calculateNonexistentKeys

2023-06-19 09:04 UTC, daneryl commented on app/api/i18n.v2/database/MongoTranslationsDataSource.ts
> +      items.map(async item =>
:+1: changed to a reduce

2023-06-19 09:10 UTC, LaszloKecskes approved these changes
Looks good!

2023-06-21 07:39 UTC, merged