5831 integrate relationship v2 migrations
huridocs/uwazidocs pull request #5862
Opened 2023-05-25 12:26 UTC by LaszloKecskes

fixes #5831 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-06-05 17:19 UTC, fnocetti requested changes
Hey, I added some comments. Please take a look. 
Other than that, I noticed there are no tests at all. Are we good with that?

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +    const groupbedByTemplate = objectIndexToArrays(
There's a typo in `groupbedByTemplate` :)

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/contracts/HubDataSource.ts
> +  all(): MongoResultSet<HubType, string>;
This needs to return an application layer ResultSet, MongoResultSet is leaking implementation.

2023-06-05 17:19 UTC, fnocetti commented on app/api/common.v2/database/data_source_defaults.ts
> +import { getClient } from 'api/common.v2/database/getConnectionForCurrentTenant';
Why was this change needed?

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/contracts/V1ConnectionsDataSource.ts
> +import { MongoResultSet } from 'api/common.v2/database/MongoResultSet';
Importing database code from the application layer is a violation to the dependency rule. Contracts need to use ResultSet

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +  shouldBeCreated() {
I think all of these `should*` methods should be private

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +const collectionExists = async (db: Db, name: string) => {
Why not make of this another private method?

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +  async create(): Promise<void> {
I don't get the idea behind the `shouldBeCreated` and `shouldNotBeDropped` logic. Why are those checks important? Wouldn't a "drop and re-create" flow be enough?

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +  allCursor(): MongoResultSet<V1ConnectionDBO, V1Connection> {
We don't usually sufix this method names with cursor. `all` should be enough.

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +    _hubIds: string[]
Prefixing with _ is usually a convention for unused parameters. If we can find a better name I would use the _ in the variable instead.

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +        $set: {
This `$set` + `$unset` combination can be performed with a single `$project`

2023-06-05 17:19 UTC, fnocetti commented on app/api/common.v2/database/MongoResultSet.ts
> +  async nextBatch(size: number): Promise<U[]> {
There's no added benefit from batching here because it is still fetching one by one. The only difference is in that this is blocking the process until it fetched `size` elements, which is not necessary good, but it's not saving any network traffic. I would just use the normal `all` and iterate over the results using the `forEach` method on the result set.

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +    while (await hubCursor.hasNext()) {
I would have just used `all` + `forEach`. Check up the comment on `MongoResultSet`

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +      for (let i = 0; i < connectionGroups.length; i += 1) {
I personally find `forEach`s much more readable than plain `for`s

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +        total += groupTotal;
Adding to previous comment, I think this is an almost perfect use case for a `reduce`

2023-06-05 17:19 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +  private transactionManager: MongoTransactionManager;
I think this is not used

2023-06-05 17:19 UTC, fnocetti commented on app/api/templates.v2/database/TemplateMappers.ts
> +        property.content || V1RelationshipProperty.ALL_MARKER,
Maybe making it optional would have done the trick. The problem with this kind of markers is that, since it is defined as `' '`, typescript will infer the type as `' ' | string` which it decide its just `string` so it's a weaker typing compared to making it optional.

2023-06-07 08:03 UTC, LaszloKecskes commented
> 

Yes. We are going to test this, when the methodology is final.

2023-06-07 08:06 UTC, LaszloKecskes commented on app/api/relationships.v2/services/MigrationService.ts
> +    const groupbedByTemplate = objectIndexToArrays(
...I mean it almost makes sense. :)

2023-06-07 08:18 UTC, LaszloKecskes commented on app/api/relationships.v2/contracts/HubDataSource.ts
> +  all(): MongoResultSet<HubType, string>;
To correct this, I needed to add lower level cursor declarations to the ResultSet (like hasNext and next), since I'm processing batches. I think that's okay, those are fairly common cursor behaviors, but take a look. If not, the alternative is that we can implement a batched forEach next to the current ordinary one.

2023-06-07 08:30 UTC, LaszloKecskes commented on app/api/relationships.v2/contracts/HubDataSource.ts
> +  all(): MongoResultSet<HubType, string>;
Scratch the above, I've went ahead and implemented the batchedForEach, since it sounded like a nice idea regardless of context.

2023-06-07 08:34 UTC, LaszloKecskes commented on app/api/common.v2/database/data_source_defaults.ts
> +import { getClient } from 'api/common.v2/database/getConnectionForCurrentTenant';
It wasn't, reverting it.

2023-06-07 08:42 UTC, LaszloKecskes commented on app/api/relationships.v2/contracts/V1ConnectionsDataSource.ts
> +import { MongoResultSet } from 'api/common.v2/database/MongoResultSet';
Seems to be a common thing I'm missing.

2023-06-07 08:43 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +  shouldBeCreated() {
Done.

2023-06-07 08:47 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +const collectionExists = async (db: Db, name: string) => {
Or rather, just add the implementation to the exists method, there's no need for a general function.

The reason (or rather, history) it's here that I first experimented in creating a generic temporary datasource with autogenerated collection names and such, but I could not make it work without leaking mongo types into the services so I've scratched it. It was close, so if we need it, we can probably make it work (if anything, as an abstract class for sure). But we don't need it.

2023-06-07 08:50 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoHubsDataSource.ts
> +  async create(): Promise<void> {
Maybe for the creation-drop, yes. But I'd like to have these checks for at least the insert functionality, and not have that auto create things and for that they are I think useful.

2023-06-07 08:53 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +  allCursor(): MongoResultSet<V1ConnectionDBO, V1Connection> {
Done.

2023-06-07 08:56 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +    _hubIds: string[]
I think we do this all the time in uwazi. Regardless, specifically for this case I've just removed the variable, since we're not reusing it, we can do the map in the db call.

2023-06-07 09:03 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +        $set: {
I've tried, it gave me:
"MongoServerError: Bad projection specification, cannot exclude fields other than '_id' in an inclusion projection:"

Maybe I've tried the wrong way, if you'd like you can give it a try in the branch.

2023-06-07 09:08 UTC, LaszloKecskes commented on app/api/common.v2/database/MongoResultSet.ts
> +  async nextBatch(size: number): Promise<U[]> {
The benefit comes not necessarily from the read side, but that one is able to do the processing more efficiently on the batch. For example, where this is used (in the migration service), callback is requesting additional data and performs write operations as well, so we save traffic there, since we're not doing that one-by-one for each hub.
Of course, at that point from the read perspective the batch is that some syntactic sugar for waiting and putting things in an array, but I think that's still worth it to make things a little bit easier.

2023-06-07 09:10 UTC, LaszloKecskes commented on app/api/relationships.v2/services/MigrationService.ts
> +    while (await hubCursor.hasNext()) {
This has been changed to a batched for each, and I'm still standing by the batching. :)

2023-06-07 09:18 UTC, LaszloKecskes commented on app/api/relationships.v2/services/MigrationService.ts
> +        total += groupTotal;
For this and the previous comment, this is definitely a question of preference. I could see the case for a forEach, but we can't do that here due to the async operation. Here, my preference is the opposite, I prefer loops for syncing promises (and in general, I don't prefer using reduce for anything else than the intended purpose in data processing, that is, providing aggregations).
We've talked about this with Joan on a couple of occasions (mostly in migration and csv import context), and we've agreed that in the end both are legible and correct, so we will allow both ways, depending on programmer preference.

2023-06-07 09:20 UTC, LaszloKecskes commented on app/api/relationships.v2/services/MigrationService.ts
> +  private transactionManager: MongoTransactionManager;
Removing it. I wanted to use it, but I'm concerned about the limits for transactions, and these operations can be quite big, and easily reversible anyway.

2023-06-07 09:24 UTC, LaszloKecskes commented on app/api/templates.v2/database/TemplateMappers.ts
> +        property.content || V1RelationshipProperty.ALL_MARKER,
We should have a dedicated discussion about this, since this has been come up, and now I'm starting to feel that we should not have undefined mean a thing aside from it's original meaning in javascript.

For this specific one, I did it, since it matches how we store it in the database. So no marker for now.

2023-06-07 11:59 UTC, fnocetti commented on app/api/relationships.v2/database/MongoV1ConnectionsDataSource.ts
> +        $set: {
Yeah, the way to do it is not to provide the include and excludes but only specify what you want yo see in the result (everything but what you want to exclude + the ones you put in the $set, that are calculated). Anyway, it's just a micro optimization

2023-06-07 11:59 UTC, fnocetti commented on app/api/templates.v2/database/TemplateMappers.ts
> +        property.content || V1RelationshipProperty.ALL_MARKER,
It's indeed a good conversation to have :)

2023-06-07 14:57 UTC, fnocetti approved these changes
Other than the fussy comment about naming, this looks good!

2023-06-07 14:57 UTC, fnocetti commented on app/api/common.v2/database/MongoResultSet.ts
> +  async batchedForEach(batchSize: number, callback: (items: U[]) => Promise<void> | void) {
I would suggest `forEachBatch` so the suggestions on the editor are more natural.

2023-06-08 09:42 UTC, merged