5928 v2 relationship migration text references
huridocs/uwazidocs pull request #5988
Opened 2023-06-28 11:01 UTC by LaszloKecskes

fixes #5928 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-06-29 22:00 UTC, fnocetti requested changes
Left some comments. Nice job on the MongoResultSet!

2023-06-29 22:00 UTC, fnocetti commented on app/api/authorization.v2/database/schemas/permissionSchemas.ts
> +const legacyObjectIdSchema = {
We're not longer using schemas but this seems not to have been removed. Do you think it makes sense to remove within this PR? Boy scout rule :)

2023-06-29 22:00 UTC, fnocetti commented on app/api/common.v2/contracts/ResultSet.ts
> +type loopCallbackReturn = Promise<void | boolean> | void | boolean;
Type names should be capitalized. Also, I would use a more descriptive name. Something like BreakLoopSignal

2023-06-29 22:00 UTC, fnocetti commented on app/api/common.v2/model/Tenant.ts
> +class Tenant {
We need to discuss this. Tenants are not an application concept. Uwazi as an application doesn't know about tenants, everything "related" to tenants is hidden from the application in the form of injected dependencies that are already instantiated for the tenant. They're only relevant to the multitenancy strategy which is only important to the process serving Uwazi, which makes it an infrastructure concern.

2023-06-29 22:00 UTC, fnocetti commented on app/api/common.v2/database/MongoResultSet.ts
> +    let progress = true;
I think we need a more descriptive name for this. Progress is usually related to how advanced te process is. I would suggest something like `shouldContinue`

2023-06-29 22:00 UTC, fnocetti commented on app/api/common.v2/contracts/ResultSet.ts
> +type loopCallbackReturn = Promise<void | boolean> | void | boolean;
Also, you can just export type here.

2023-06-29 22:00 UTC, fnocetti commented on app/api/relationships.v2/services/MigrationService.ts
> +      `V2 Relationship Migration Error (tenant:${this.tenant.name})----------------------------------`
Instead of putting the tenant name here, this service should be injected with a tenant specific logger.

2023-06-30 07:23 UTC, LaszloKecskes commented on app/api/common.v2/contracts/ResultSet.ts
> +type loopCallbackReturn = Promise<void | boolean> | void | boolean;
Done.

2023-06-30 07:24 UTC, LaszloKecskes commented on app/api/common.v2/database/MongoResultSet.ts
> +    let progress = true;
Done.

2023-06-30 07:25 UTC, LaszloKecskes commented on app/api/common.v2/contracts/ResultSet.ts
> +type loopCallbackReturn = Promise<void | boolean> | void | boolean;
Did we not have an eslint rule for exporting things at the end?

Done.

2023-06-30 07:41 UTC, LaszloKecskes commented on app/api/authorization.v2/database/schemas/permissionSchemas.ts
> +const legacyObjectIdSchema = {
No, since I found a couple of others as well (unrelated to this development). Wrote an issue for it (#5991), and assigned to myself to be done right after this. It should not take long.

2023-06-30 09:48 UTC, LaszloKecskes commented on app/api/common.v2/model/Tenant.ts
> +class Tenant {
Will remove this in favor of the logger.

2023-06-30 09:48 UTC, LaszloKecskes commented on app/api/relationships.v2/services/MigrationService.ts
> +      `V2 Relationship Migration Error (tenant:${this.tenant.name})----------------------------------`
As above; will do so.

2023-07-10 12:01 UTC, fnocetti requested changes
Mostly looks good to me! Only a few comments on the logger side :)

2023-07-10 12:01 UTC, fnocetti commented on app/api/log.v2/contracts/LoggerInterfaces.ts
> +export interface LogLevelInterface {
`LogLevelInterface` and `LogEntryInterface` are internal to the implementation. I think they should be within the `infrastructure/Logger.ts` file. Nevertheless, it looks like an interface for those is not needed since, again, they are implementation details and it doesn't look like there's going to be a need for second implementations.

2023-07-10 12:01 UTC, fnocetti commented on app/api/log.v2/contracts/LoggerInterfaces.ts
> +export interface LoggerInterface {
Please, let's kindly remove the interface postfix, it's redundant and we don't usually signal that in the class/interface names.

2023-07-10 12:01 UTC, fnocetti commented on app/api/log.v2/infrastructure/Logger.ts
> +  DEBUG: new LogLevel('DEBUG', 10),
If there's going to always be a single application-wise instance of each log level I think it makes more sense to just have plain objects, in which case an interface makes sense for typing purposes.

2023-07-11 07:21 UTC, LaszloKecskes commented on app/api/log.v2/contracts/LoggerInterfaces.ts
> +export interface LogLevelInterface {
Agree with the internal implementation, removed.

2023-07-11 07:22 UTC, LaszloKecskes commented on app/api/log.v2/contracts/LoggerInterfaces.ts
> +export interface LoggerInterface {
Done. I've kept one place: since we now call everything Logger, one needs to disambiguate in the implementation, so:
`import { Logger as LoggerInterface } from '../contracts/Logger';`

2023-07-11 07:28 UTC, LaszloKecskes commented on app/api/log.v2/infrastructure/Logger.ts
> +  DEBUG: new LogLevel('DEBUG', 10),
Locally, I think they are fairly equivalent (up to preference :)), since I think they are equally readable, and for this amount of objects the class overhead is negligible. The reason I would still keep it is that I expect that we will have some other functionality for LogLevels, where it will make sense to have a class for encapsulation. For example, one natural evolution of this is to use this frequently, and have the loglevel as a configuration when starting up the Uwazi server, so a comparison would then be necessary.

If you think we should wait to do a class until we need it, that's fine and I'll change it, but I think it's okay to "expect the future" this much, especially since it is no extra effort.

2023-07-11 13:48 UTC, fnocetti commented on app/api/log.v2/infrastructure/Logger.ts
> +  DEBUG: new LogLevel('DEBUG', 10),
Sounds good!

2023-07-11 13:49 UTC, fnocetti approved these changes
LGTM!

2023-07-12 07:53 UTC, merged