Relationships v2 migration user choice
huridocs/uwazidocs pull request #6037
Opened 2023-07-13 10:08 UTC by LaszloKecskes

fixes #6002 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-07-25 22:38 UTC, fnocetti requested changes
Overall looks good, please take a look at the comments.

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/database/MongoMigrationHubRecordDataSource.ts
> +    return resultset.page(page, pageSize);
The page method in the ResultSet is there so we don't have to implement getPage in the data sources. The service gets a ResultSet and it should be up to it to consume it as a page.

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +  RelationShipMigrationFieldUniqueId,
I think there's a type with the capital S in Relation*S*hip.

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +  async get(fieldId: RelationShipMigrationFieldUniqueId): Promise<RelationshipMigrationField> {
I think we use to call this methods getById, don't we?

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +      throw new Error(`Field with id ${fieldId} not found`);
I may be missing something, but by convention we return null/undefined and perform a check in the consumer. I don't think looking for a non-existing record is a data access error.

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/routes/routes.ts
> +    '/api/v2/relationshipMigrationFields/create',
Why not use `POST relationshipMigrationFields` and `PUT relationshipMigrationFields` instead of `/create` and `/update`?

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/services/CreateRelationshipMigrationFieldService.ts
> +      return this.fieldDS.get(field.id);
I think we usually return the newly created object from the `create` method. While it is a probably imperceptible optimization, it also doesn't require another query since you already have the object in memory, and Mongo will provide you with the created id, in case you needed it.
In this particular case, I don't even think you need to get. If the save was successful, then the object you have in memory is the same thing the get will return, right?

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/services/DeleteRelationshipMigrationFieldService.ts
> +      const fieldId = new RelationShipMigrationFieldUniqueId(
Can we move this outside of the transaction? So if in the future there are some checks to fail, it will do so before even starting the transaction.

2023-07-25 22:38 UTC, fnocetti commented on app/api/relationships.v2/services/GetRelationshipMigrationFieldService.ts
> +    await this.transactionManager.run(async () => {
I don't think this needs a transaction

2023-07-25 22:38 UTC, fnocetti commented on app/shared/data_utils/specs/stringUtils.spec.ts
> +    'should compare lists based on alphabetical order as localeCompare does',
Isn't it called lexicographical order? :)

2023-07-25 22:38 UTC, fnocetti commented on app/api/common.v2/contracts/Sink.ts
> +interface Sink<T> {
I like the concept, I'm not sure about the name. I would attach to SaveStream, the same way you named the implementation, factory method and variables.

2023-07-26 08:11 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoMigrationHubRecordDataSource.ts
> +    return resultset.page(page, pageSize);
Done.

2023-07-26 08:14 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +  RelationShipMigrationFieldUniqueId,
Indeed.

2023-07-26 08:25 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +  async get(fieldId: RelationShipMigrationFieldUniqueId): Promise<RelationshipMigrationField> {
Sure.

2023-07-26 08:30 UTC, LaszloKecskes commented on app/api/relationships.v2/services/GetRelationshipMigrationFieldService.ts
> +    await this.transactionManager.run(async () => {
Nice catch.

2023-07-26 08:38 UTC, LaszloKecskes commented on app/api/relationships.v2/services/CreateRelationshipMigrationFieldService.ts
> +      return this.fieldDS.get(field.id);
Done, same for upsert.

2023-07-26 08:43 UTC, LaszloKecskes commented on app/api/relationships.v2/database/MongoRelationshipMigrationFieldsDataSource.ts
> +      throw new Error(`Field with id ${fieldId} not found`);
Due to changes in the create and upsert services, this is not used anymore, so I ended up removing entirely.

2023-07-26 08:50 UTC, LaszloKecskes commented on app/api/relationships.v2/routes/routes.ts
> +    '/api/v2/relationshipMigrationFields/create',
Done.

2023-07-26 08:51 UTC, LaszloKecskes commented on app/api/relationships.v2/services/DeleteRelationshipMigrationFieldService.ts
> +      const fieldId = new RelationShipMigrationFieldUniqueId(
Of course.

2023-07-26 08:55 UTC, LaszloKecskes commented on app/api/common.v2/contracts/Sink.ts
> +interface Sink<T> {
That was the original idea, then I've noticed that this is a more general interface for any kind of consumer. Also, I'm hesitant to use the word stream unless we're really starting to move towards proper stream processing. Nevertheless, I'll rename it for now, then we can revisit it later when we're using it for anything else.

2023-07-26 23:42 UTC, fnocetti approved these changes
LGTM!

2023-07-26 23:42 UTC, fnocetti commented on app/api/common.v2/contracts/Sink.ts
> +interface Sink<T> {
Agree with you

2023-07-27 11:57 UTC, merged