I16 csv export endpoint change
huridocs/uwazidocs pull request #6065
Opened 2023-08-03 08:47 UTC by LaszloKecskes

fixes [i16](https://github.com/huridocs/Internal-Issues/issues/16), [i11](https://github.com/huridocs/Internal-Issues/issues/11)

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-08-03 15:25 UTC, Zasa-san commented on app/react/Library/actions/exportActions.ts
> +const requestHandler = (_params: any, dispatch: Dispatch<any>, captcha?: CaptchaValue) => {
can `_params` by typed as `CsvExportParams`?

2023-08-03 23:20 UTC, fnocetti requested changes
Other than the typing comment, LGTM!

2023-08-03 23:20 UTC, fnocetti commented on app/api/files/exportRoutes.ts
> +        const query: any = { ...req.body };
Could we type this with the newly created type?

2023-08-04 08:18 UTC, LaszloKecskes commented on app/react/Library/actions/exportActions.ts
> +const requestHandler = (_params: any, dispatch: Dispatch<any>, captcha?: CaptchaValue) => {
Almost. I needed to add some extra for the ids, since those are coming from the store and are Immutable.
```
CsvExportBody & { ids?: List<string> }
```
Also, while I've done it, I don't know how useful it is, since the values ultimately come from an un-typed js file.

2023-08-04 08:19 UTC, LaszloKecskes commented on app/api/files/exportRoutes.ts
> +        const query: any = { ...req.body };
Done.

2023-08-04 11:20 UTC, fnocetti approved these changes
LGTM!

2023-08-04 11:48 UTC, merged