5960 fix live translate on language addition
huridocs/uwazidocs pull request #6093
Opened 2023-08-25 09:25 UTC by LaszloKecskes

fixes #5960 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-08-28 13:14 UTC, fnocetti requested changes
Apart from minor comments, up to you to change, it LGTM and works as expected.

2023-08-28 13:14 UTC, fnocetti commented on app/shared/asyncUtils.ts
> +const sequentialPromises = async <T>(
Since this takes a collection and an async function to be executed on each sequentially, I think this is actually an async version of a forEach. I would inspire the name from there.

2023-08-28 13:14 UTC, fnocetti commented on app/shared/asyncUtils.ts
> +    await previousPromise.then(async () => asyncCallback(element, index, originalArray));
The then callback can also be awaited:
```
await previousPromise;
await asyncCallback(element, index, originalArray);
```

2023-08-29 06:24 UTC, LaszloKecskes commented on app/shared/asyncUtils.ts
> +    await previousPromise.then(async () => asyncCallback(element, index, originalArray));
Done.

2023-08-29 07:58 UTC, merged