5469 numeric fields validation
huridocs/uwazidocs pull request #6137
Opened 2023-09-07 14:33 UTC by fnocetti

fixes #5469 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-09-12 07:27 UTC, LaszloKecskes commented on app/api/migrations/migrations/142-parse-numeric-fields/index.ts
> +      if (Object.keys(updates).length > 0) {
Consider using bulk write with some batch size. In my experience that can speed up entity based migrations a lot.

2023-09-12 07:28 UTC, LaszloKecskes requested changes
Aside from the one comment, it looks good and works!

2023-09-12 21:12 UTC, fnocetti commented on app/api/migrations/migrations/142-parse-numeric-fields/index.ts
> +      if (Object.keys(updates).length > 0) {
Nice catch, done!

2023-09-13 12:59 UTC, LaszloKecskes approved these changes

2023-09-15 06:40 UTC, LaszloKecskes approved these changes

2023-09-15 12:47 UTC, merged