6110 add missing tests for commonv2
huridocs/uwazidocs pull request #6149
Opened 2023-09-18 07:24 UTC by LaszloKecskes

Part of, but does not completely solve #6110.

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-09-18 13:50 UTC, fnocetti requested changes
Overall looks good! Only a few comments.

2023-09-18 13:50 UTC, fnocetti commented on app/api/common.v2/database/specs/MongoIdGenerator.spec.ts
> +      expect(MongoIdHandler.mapToDb(id)).toEqual(expect.any(ObjectId));
This should test the implementation. That is: that the id is mapped to the correct string. 
Maybe manually create an ObjectId so you can beforehand know the string without having to reimplement the mapper for the sake of testing.

2023-09-18 13:50 UTC, fnocetti commented on app/api/common.v2/database/specs/MongoIdGenerator.spec.ts
> +      expect(MongoIdHandler.mapToApp(MongoIdHandler.mapToDb(id))).toEqual(id);
Same as previous.

2023-09-18 13:50 UTC, fnocetti commented on app/api/authorization.v2/database/specs/data_source_defaults.spec.ts
> +      expect(DefaultPermissionsDataSource()).toBeInstanceOf(MongoPermissionsDataSource);
Now it's done, that's fine. But I don't know if this merits tests. This is exactly what types are for.

2023-09-19 12:04 UTC, LaszloKecskes commented on app/api/common.v2/database/specs/MongoIdGenerator.spec.ts
> +      expect(MongoIdHandler.mapToDb(id)).toEqual(expect.any(ObjectId));
Good one, will do.

2023-09-19 12:05 UTC, LaszloKecskes commented on app/api/common.v2/database/specs/MongoIdGenerator.spec.ts
> +      expect(MongoIdHandler.mapToApp(MongoIdHandler.mapToDb(id))).toEqual(id);
Same as previous. :)

2023-09-19 12:07 UTC, LaszloKecskes commented on app/api/authorization.v2/database/specs/data_source_defaults.spec.ts
> +      expect(DefaultPermissionsDataSource()).toBeInstanceOf(MongoPermissionsDataSource);
I think, strictly speaking, on the type level the defaults return the interface, because the users (i.e. the services) need only know about that aspect. I think there's value in having tests that explicitly say in the code base that at this point in time, the expected default we have decided on is the Mongo version of whatever DS we look at. At least as a reminder if we ever have anything else and decide to change.

2023-09-19 12:14 UTC, fnocetti approved these changes

2023-09-20 07:44 UTC, merged