6217 any template relationship deletion fix
huridocs/uwazidocs pull request #6226
Opened 2023-10-25 09:52 UTC by LaszloKecskes

fixes #6217 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2023-10-29 16:14 UTC, fnocetti requested changes
It doesn't work for me. In line 730 it is trying to load the templates that have a property with that content configured, which is not the case, since the only property I have is the one described in the issue with no content.

2023-10-29 16:14 UTC, fnocetti commented on app/api/entities/entities.js
> +      (!p.content && p.content === '');
The property schema says that the content is optional. Why are we allowing falsy values only when they're empty strings?

2023-10-30 08:40 UTC, LaszloKecskes commented
> It doesn't work for me. In line 730 it is trying to load the templates that have a property with that content configured, which is not the case, since the only property I have is the one described in the issue with no content.

And I did not notice this, because the test case in the fixtures had two relationships, and while doing the manual testing, I did the same. Embarrassing. Thanks!

2023-10-30 08:43 UTC, LaszloKecskes commented on app/api/entities/entities.js
> +      (!p.content && p.content === '');
As usual, the content is optional, because we're handling every property in one schema, so everything is optional aside from the shared base (label, name, type). When we're creating the relationship to any template, an empty string gets written to the db, so a not-existing content means a property where content does not have a meaning, rather than the any template case.
However, empty strings are falsy anyway so you are right, this is redundant.

2023-10-31 03:15 UTC, fnocetti commented
It looks good and it works as expected. I was just thinking that this may need a migration. Let's discuss it with the team.

2023-11-07 09:28 UTC, LaszloKecskes commented
> It looks good and it works as expected. I was just thinking that this may need a migration. Let's discuss it with the team.

After the discussion, we have decided to add the migration.

2023-11-13 14:32 UTC, fnocetti approved these changes
Appart from the comment, approved. Looks good and works.

2023-11-13 14:32 UTC, fnocetti commented on app/api/migrations/migrations/149-remove_inconsistent_relationships_metadata/specs/fixtures.ts
> +const noReindexFixtures: FixtureType = {
What does `noReindexFixtures` mean?

2023-11-13 14:39 UTC, LaszloKecskes commented on app/api/migrations/migrations/149-remove_inconsistent_relationships_metadata/specs/fixtures.ts
> +const noReindexFixtures: FixtureType = {
If a migration might involve reindexing, I usually try to test a case where it should not reindex. In this case, if none of the entities needed changing, we should not reindex. These are the part of the fixtures that will remain unchanged. We could remain it to something else to make it more semantic.

2023-11-13 15:02 UTC, fnocetti commented on app/api/migrations/migrations/149-remove_inconsistent_relationships_metadata/specs/fixtures.ts
> +const noReindexFixtures: FixtureType = {
That makes sense, thanks!

2023-11-14 09:08 UTC, merged