Custom page error fix
huridocs/uwazidocs pull request #6329
Opened 2023-12-19 09:20 UTC by grafitto

fixes #6250 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2024-01-24 21:24 UTC, Zasa-san requested changes
The bug seems fixed! Nice!

2024-01-24 21:24 UTC, Zasa-san commented on app/react/entry-server.tsx
> +    // @ts-ignore
Please check if we can use types in the few `@ts-ignore`s.

2024-01-24 21:24 UTC, Zasa-san commented on app/react/entry-server.tsx
> +        // console.log(e.json.errors);
Please remove the logs, there's a couple of them :grimacing:

2024-01-24 21:24 UTC, Zasa-san commented on e2e/suite1/pages.test.ts
> +  it('should allow using a complicated library query as a landing page', async () => {
Is there a unit test where you could test with more diverse cases? It's OK to have it covered by an E2E, but in my opinion this type of things should be tested in the E2E in a rather simple way, and heavily tested in unit tests. That said, I defer to your opinion on this.

2024-01-24 21:24 UTC, Zasa-san commented on app/react/getIndexElement.tsx
> +  if (query) {
Codeclimate is complaining about this, maybe we can refactor the nested `if`s a bit

2024-01-28 08:11 UTC, grafitto commented on app/react/entry-server.tsx
> +    // @ts-ignore
Removed

2024-01-28 08:12 UTC, grafitto commented on app/react/entry-server.tsx
> +        // console.log(e.json.errors);
Removed

2024-01-28 08:14 UTC, grafitto commented on app/react/getIndexElement.tsx
> +  if (query) {
Fixed

2024-01-28 08:25 UTC, grafitto commented on app/react/getIndexElement.tsx
> +  if (query) {
Done

2024-01-30 12:44 UTC, grafitto commented
Just realized this fixes a critical issue. Will create another how fix then close this.

2024-01-30 12:47 UTC, grafitto commented
> Just realized this fixes a critical issue. Will create another how fix then close this.

https://github.com/huridocs/uwazi/pull/6402 here is the hotfix

2024-01-30 12:47 UTC, closed without merging