Supplement missing entity templates
huridocs/uwazidocs pull request #6555
Opened 2024-02-28 10:46 UTC by LaszloKecskes

fixes #

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2024-03-06 19:32 UTC, fnocetti requested changes
The code looks good, but I think it's missing the translations context. I will proceed to the manual testing.

2024-03-07 08:53 UTC, LaszloKecskes commented
> ...but I think it's missing the translations context. 

Indeed, it does. Nice catch.

2024-03-08 03:18 UTC, fnocetti requested changes
It works as expected. Left one comment that needs addressing.

2024-03-08 03:18 UTC, fnocetti commented on app/api/migrations/migrations/162-supplement-missing-entity-templates/specs/162-supplement-missing-entity-templates.spec.ts
> +        color: '##ff0000',
The hex color should be prefixed with 1 single #

2024-03-08 08:16 UTC, LaszloKecskes commented on app/api/migrations/migrations/162-supplement-missing-entity-templates/specs/162-supplement-missing-entity-templates.spec.ts
> +        color: '##ff0000',
Corrected.

2024-03-08 13:48 UTC, fnocetti approved these changes
LGTM!

2024-03-12 14:54 UTC, merged