No more migrations for translations
huridocs/uwazidocs pull request #6594
Opened 2024-03-15 11:03 UTC by konzz

fixes #

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2024-03-19 19:44 UTC, mfacar requested changes
Great job! It's a super improvement. While testing I found a problem with the command to update the database, it is deleting entries for contexts different from 'System', like template properties and menu items.

Also, please don't forget the observation from @Zasa-san, about a check between the differences of the CSV files across languages.

2024-03-19 19:44 UTC, mfacar commented on scripts/updateTranslationsCSV.mjs
> +          file.endsWith('.jsx'))
This condition could be simplified with something like: ```!file.match(/(\.spec|stories|\.cy)/) && file.match(/(\.js|\.ts|\.tsx|\.jsx)$/)```, what do you think?

2024-03-19 19:44 UTC, mfacar commented on scripts/updateTranslationsCSV.mjs
> +const getKeysFromRepository = async (locale = 'en') =>
In order to avoid duplication, what about extracting this and getAvailableLanguages into a new file that exports them as `module.exports = { getKeysFromRepository, getAvailableLanguages };`

2024-03-22 08:33 UTC, konzz commented
Closing PR to create a new one pointing to production

2024-03-22 08:33 UTC, closed without merging