HOTFIX 6217 any relationships empty content hotfix
huridocs/uwazidocs pull request #6789
Opened 2024-05-21 13:22 UTC by fnocetti

fixes #6217 

PR checklist:
- [ ] Update READ.me ?
- [ ] Update API documentation ?

QA checklist:
- [ ] Smoke test the functionality described in the issue
- [ ] Test for side effects
- [ ] UI responsiveness
- [ ] Cross browser testing
- [ ] Code review

2024-05-23 07:27 UTC, LaszloKecskes commented on app/api/entities/specs/fixtures.js
> +          // No content set to test no content apart from content: ""
Is the `content: ''` case still tested somewhere?

2024-05-23 08:14 UTC, LaszloKecskes requested changes
Confirmed working as intended locally, by manually removing content from a template to test the situation described in the issue.

Code looks good, one question in a test.

2024-05-27 12:59 UTC, fnocetti commented on app/api/entities/specs/fixtures.js
> +          // No content set to test no content apart from content: ""
Yes, there's a case here: https://github.com/huridocs/uwazi/pull/6789/files#diff-7d284794be370388a325e4eaeb22025f7d0d71d26541459d7d287af920abb546L586

2024-05-27 13:01 UTC, LaszloKecskes commented on app/api/entities/specs/fixtures.js
> +          // No content set to test no content apart from content: ""
Thanks!

2024-05-27 13:02 UTC, LaszloKecskes approved these changes

2024-05-28 20:10 UTC, fnocetti commented
I'm merging as we agreed the failing test is unrelated.

2024-05-28 20:10 UTC, merged